---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentvolume.name }}
spec:
  accessModes:
  {{- range $mode := .Values.persistentvolume.accessModes }}
  - {{ . }}
  {{- end }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.resources.requests.storage }}
  selector:
    matchLabels:
      type: nfs
