{{- if .Values.inject_secret -}}
{{- $inject_secret := .Values.inject_secret }}
{{- range $secret := $inject_secret.secret.object }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $secret }}
  namespace: {{ $inject_secret.namespace }}
spec:
  vault:
    name: {{ $inject_secret.vault.name }}
    object:
      name: {{ $secret }}
      type: secret
{{- end }}
{{- end }}
