{{- range $secret := .Values.inject_secret.secret }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $secret }}
  namespace: {{ .Values.inject_secret.namespace }}
spec:
  vault:
    name: {{ .Values.inject_secret.vault.name }}
    object:
      name: {{ $secret }}
      type: secret
{{- end }}
