{{- if .Values.sync_secret_to_configmap -}}
{{- $sync_secret_to_configmap := .Values.sync_secret_to_configmap }}
{{- range $secret := $sync_secret_to_configmap.secret.object }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $secret }}
  namespace: {{ $sync_secret_to_configmap.namespace }}
spec:
  vault:
    name: {{ $sync_secret_to_configmap.vault.name }}
    object:
      name: {{ $secret }}
      type: secret
  output:
    configMap:
      name: {{ $sync_secret_to_configmap.configmap.name }}
      dataKey: {{ $secret }}
{{- end }}
{{- end }}
