{{- if .Values.sync_secret -}}
{{- $sync_secret := .Values.sync_secret }}
{{- range $secret := $sync_secret.secret.object }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $secret }}
  namespace: {{ $sync_secret.namespace }}
spec:
  vault:
    name: {{ $sync_secret.vault.name }}
    object:
      name: {{ $secret }}
      type: secret
  output:
    secret:
      name: {{ $secret }}
      dataKey: value
{{- end }}
{{- end }}
