name: shopware
namespace: default
replicas: 1
service:
  ports:
  - protocol: TCP
    port: 80
deployment:
  containers:
    imagePullPolicy: "IfNotPresent"
    resources:
      requests:
        memory: "300Mi"
        cpu: "0.2"
        ephemeral_storage: "1500Mi"
      limits:
        memory: "600Mi"
        cpu: "0.4"
        ephemeral_storage: "1500Mi"
    lifecycle: |
      postStart:
        exec:
          command: ["/bin/sh", "-c", "cd /var/www/html/public; bin/console database:migrate --all"]
    ports:
    - name: http
      containerPort: 80
    readinessProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    livenessProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    startupProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      failureThreshold: 10
      periodSeconds: 30
    volumeMounts:
      fileadmin:
        mountPath: "/var/www/html/public/public/media"
        subPath: "media"
      uploads:
        mountPath: "/var/www/html/public/public/thumbnail"
        subPath: "thumbnail"
persistentvolume:
  name: nfs
  capacity:
    storage: "10Gi"
  accessModes:
  - ReadWriteMany
  nfs:
    server: "nfs-server.default.svc.cluster.local"
    volume: "/"
    path: "/"
persistentvolumeclaim:
  resources:
    requests:
      storage: 1Gi
