{{- if .Values.ingress -}}
{{- $ingress := .Values.ingress -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  namespace: {{ $ingress.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- range $key, $value := $ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  # check if defaultBackend should be set
  {{- if keys $ingress.defaultBackend }}
  defaultBackend:
    {{- if $ingress.defaultBackend.service }}
    service:
      name: {{ $ingress.defaultBackend.service.name }}
      port:
        number: {{ $ingress.defaultBackend.service.port.number }}
    {{- end }}
  {{- end }}
  # check if rules should be set
  {{- if $ingress.rules }}
  rules:
  # loop over rules keys
  {{- range $rule := $ingress.rules }}
  # loop over host list for same paths settings
  {{- range  $rule.host }}
  - host: {{ . }}
    http:
      paths:
      # loop over paths configuration
      {{- range $path := $rule.http.paths }}
        - path: {{ $path.path }}
          pathType: {{ $path.pathType }}
          backend:
            service:
              name: {{ $path.backend.service.name }}
              port:
                number: {{ $path.backend.service.port.number }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}
