---
name: New release

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: create release draft
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
